### ISSUE TITLE
Add USB Serial Converter Support

### ISSUE THREAD

**Issue by DroidKali** [cyberknight777/android_kernel_nethunter#1]
Add USB serial Converter Driver support like CH340G and CP2102 FTDI USB2TTL support

*Device Drivers→USB Support→USB Serial Converter Support*
![USB Serial Support](https://z3.ax1x.com/2021/08/05/fefrqg.png)

**Comment by 0n1cOn3** [comment]
We focus on Nethunter relevant modifications. I am not aware of anything that could be done with a serial interface. I would be happy to be taught better.

**Comment by Anonym3310** [comment]
And what are they for?

**Comment by cyberknight777** [comment]
You know, instead of opening an issue, you could have dropped a PR with the additions.

**Comment by DroidKali** [comment]
Done , see #3
